### ISSUE TITLE
[ ] Unrecognized TLS error - this must be patched manually

### ISSUE THREAD

**Issue by pb36** [httptoolkit/frida-interception-and-unpinning#88]
App-Tata NeU
Command used - `frida -U -l config.js -l native-tls-hook.js -l android-certificate-unpinning.js -l android-certificate-unpinning-fallback.js -f com.tatadigital.tcp`

`     ____
    / _  |   Frida 16.2.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to ONEPLUS A5000 (id=192.168.1.5:5555)
Spawning `com.tatadigital.tcp`...

== Hooked native TLS lib libssl.so ==
Spawned `com.tatadigital.tcp`. Resuming main thread!
[ONEPLUS A5000::com.tatadigital.tcp ]-> [!] Matched class okhttp3.CertificatePinner but could not patch any methods
== Certificate unpinning completed ==
== Unpinning fallback auto-patcher installed ==

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive
      [ ] Unrecognized TLS error - this must be patched manually
Process crashed: java.lang.RuntimeException: DP: 751

***
FATAL EXCEPTION: main
Process: com.tatadigital.tcp, PID: 24959
java.lang.RuntimeException: Unable to create application com.tatadigital.tcp.ProtectedNeuApplication: com.tatadigital.tcp.MessageGuardException_RFA6IDc1MSBbMjAyMzA4MzEtMjAyNDAzMTkxNTE0IGI3OmFybTY0LXY4YSAyOCBPbmVQbHVzL09uZVBsdXM1L09uZVBsdXM1OjkvUEtRMS4xODA3MTYuMDAxLzE4MTIyMzIwNDY6dXNlci9yZWxlYXNlLWtleXMgYmxvY2tlZF0: DP: 751
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6044)
        at android.app.ActivityThread.handleBindApplication(Native Method)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tatadigital.tcp.MessageGuardException_RFA6IDc1MSBbMjAyMzA4MzEtMjAyNDAzMTkxNTE0IGI3OmFybTY0LXY4YSAyOCBPbmVQbHVzL09uZVBsdXM1L09uZVBsdXM1OjkvUEtRMS4xODA3MTYuMDAxLzE4MTIyMzIwNDY6dXNlci9yZWxlYXNlLWtleXMgYmxvY2tlZF0: DP: 751
        at com.tatadigital.tcp.ProtectedNeuApplication.fxiB(Unknown Source:78)
        at com.tatadigital.tcp.ProtectedNeuApplication.onCreate(Unknown Source:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039)
        ... 9 more
Caused by: java.lang.RuntimeException: DP: 751
        at com.tatadigital.tcp.ProtectedNeuApplication.J(Native Method)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tatadigital.tcp.ProtectedNeuApplication$ProtectedNeuApplication$DataBinderMapperImpl.ozbefaclio(Unknown Source:31)
        at com.tatadigital.tcp.ProtectedNeuApplication$ProtectedNeuApplication$DataBinderMapperImpl.aHikix(Unknown Source:472)
        at com.tatadigital.tcp.ProtectedNeuApplication.J(Native Method)
        at com.tatadigital.tcp.ProtectedNeuApplication.onCreate(Unknown Source:46)
        ... 11 more
***
[ONEPLUS A5000::com.tatadigital.tcp ]->

Thank you for using Frida!`

URL, which they were trying to access and failed -> aws-gate.licelus.com
so most probably they are using some sdk from licelus.com to protect against this

**Comment by pimterry** [comment]
This isn't certificate pinning - it's just a normal system CA certificate check.

Before worrying about certificate pinning, you need to ensure the Android device trusts your MITM CA as a system-level CA certificate or _all_ intercepted HTTPS connections will fail for more-or-less all apps (except ones that allow user certificates, such as Chrome or debug-enabled apps).

You can either do so by configuring that for your whole device (requires either quite a bit of manual setup, or using the one-click HTTP Toolkit ADB option on a rooted device) so that the cert appears in the system CAs in your settings, or you can use the `./android/android-system-certificate-injection.js` script here which does that directly for the target app.

Does that make sense?

**Comment by pb36** [comment]
I realized I've already been using the HTTP Toolkit (Pro) ADB option. However, even with this option enabled, the app remains open for about 10 to 15 seconds(only this specific app. Other apps seem fine, and I can record traffic as needed). I can see requests in the View Section during this time, but then it suddenly crashes. Interestingly, when I don't use the HTTP Toolkit, the app functions normally, and I can use it without any issues.

**Comment by pimterry** [comment]
> the app remains open for about 10 to 15 seconds

If you're not seeing any failing network requests at all, then this sounds like root/frida/proxy/etc detection, where the app is actively closing itself when it realises that something unusual is going on, independent of network traffic.

Fixing that is a bit more complicated unfortunately, and will likely require some reverse engineering (guide: https://httptoolkit.com/blog/android-reverse-engineering/) to work out exactly what triggers this and how to disable it. A good place to start is looking at the adb logcat output (`adb logcat -T1`) when the app closes, to see if any clues appear there.

I haven't seen any messages about this app in the past, so if you do find any clues I'd definitely be interested to hear about them. I'll keep this issue open and an eye out for related fixes that might help with this case.

**Comment by miraserver** [comment]
mmm i have same error but problem is
- before iv use old manual and old JS frida scripts posted by httptoolkit
Of course its worked perfect. But not all req possible detected
Now i v try to use new scripts posted here. And got this error. Yeap, my proxy cert already imported and trusted by my device (android), iv checked it again.
But error same here. Iv use Charles proxy, adnroid and PC, frida 16.1.11, android 10

**Comment by miraserver** [comment]
ahhh i seee, need make cert as system, not as user. But android-system-certificate-injection.js not working for it.

**Comment by pimterry** [comment]
> ahhh i seee, need make cert as system, not as user. 

Yes - you need to either trust the cert system-wide (so most apps without pinning already trust it successfully) or you need to use the `android-system-certificate-injection` script.

> But android-system-certificate-injection.js not working for it.

Can you explain exactly what "not working" means? It would be helpful to share the specific app you're testing against, the output you're seeing, and any other details about what's going wrong.

**Comment by pimterry** [comment]
> Now its working and no any error

You added this in an edit - does that mean everything is now working perfectly now, or are there still issues?

If it's not all resolved, can you please share the specific app you're testing again, and the full output that's printed by Frida when you run this command?

I'm also not clear what the `28465` is here - are you attaching to a PID, or launching an Android app? Normally you'd use `-f <package id>` with the Android package name (like `-f com.google.android.maps`)

**Comment by binbon2d** [comment]
I install AlwaysTrustUserCerts for AlwaysTrustUserCerts  but still error
1. Frida inject all comp completed
frida -U -l ./config.js -l ./native-connect-hook.js -l ./native-tls-hook.js -l ./android/android-proxy-override.js -l ./android/android-system-certificate-injection.js -l ./android/android-certificate-unpinning.js -l ./android/android-certificate-unpinning-fallback.js -p 24893
2. Request from App ==> Error
![image](https://github.com/user-attachments/assets/051a66bf-27ed-42d2-9d17-0abe32f41138)

**Comment by pimterry** [comment]
@binbon2d these scripts are intended to be used when launching a process, but the command you've listed above is attaching to an existing process. That's likely to fail in various ways, since the scripts won't be able to hook the instantiation of various objects as expected.

If you try intercepting the same app as a fresh launch instead of attaching (using the `-f $PACKAGE_ID` instead of `-p $PID`) does it work for you?

**Comment by rams3sh** [comment]
I faced same issue while spawning the process . Logs below :- 
```
(env) ram@system:~/Applications/frida/frida-interception-and-unpinning (main)$ frida -U     -l ./config.js     -l ./native-connect-hook.js     -l ./native-tls-hook.js     -l ./android/android-proxy-override.js     -l ./android/android-system-certificate-injection.js     -l ./android/android-certificate-unpinning.js     -l ./android/android-certificate-unpinning-fallback.js     -l ./android/android-disable-root-detection.js     -f <REDACTED>
     ____
    / _  |   Frida 17.2.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to <REDACTED>
Spawning `<REDACTED>`...                                   

== Redirecting all TCP connections to 192.168.0.108:8080 ==
== Hooked native TLS lib libssl.so ==
== Disabled Android root detection ==
Spawned `<REDACTED>`. Resuming main thread!                
[<REDACTED> ]-> == Proxy system configuration overridden to 192.168.0.108:8080 ==
== Proxy configuration overridden to 192.168.0.108:8080 ==
== System certificate trust injected ==
== Certificate unpinning completed ==
== Unpinning fallback auto-patcher installed ==
Manually intercepting tcp6 connection to <REDACTED>
 => Blocked possible root detection checks. Enable DEBUG_MODE for more details.
Manually intercepting tcp6 connection to <REDACTED>

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive
      [ ] Unrecognized TLS error - this must be patched manually

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->verifyChain
      [ ] Unrecognized TLS error - this must be patched manually
Manually intercepting tcp6 connection to <REDACTED>
Manually intercepting tcp6 connection to <REDACTED>
Manually intercepting tcp6 connection to <REDACTED>

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->verifyChain
      [ ] Unrecognized TLS error - this must be patched manually
Manually intercepting tcp6 connection to <REDACTED>

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive
      [ ] Unrecognized TLS error - this must be patched manually

 !!! --- Unexpected TLS failure --- !!!

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive
      [ ] Unrecognized TLS error - this must be patched manually
      CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      Thrown by com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive
      [ ] Unrecognized TLS error - this must be patched manually

<REDACTED> 

Thank you for using Frida!
```

Screenshot snippet below :- 

<img width="1250" height="581" alt="Image" src="https://github.com/user-attachments/assets/aac1c170-5e7b-4199-a108-c8c098159c58" />

**Comment by benwaffle** [comment]
I was able to reproduce the bug by running frida on `com.google.android.gms` and toggling the Phone Number Verification switch in the google settings page.

I had copilot help me fix this error. I've pushed the fix to my fork below. Unfortunately the diff is huge and I don't really understand it, but I hope this is somewhat helpful.

https://github.com/benwaffle/frida-interception-and-unpinning/commit/f84b643f410c4e3ac793464a520d1928ee6693cc

I asked copilot to summarize the fix:

> This change fixes TLS handshake failures (“Trust anchor for certification path not found”) by adding targeted fallbacks in the Android/GMS trust path that only activate when the chain is valid under the injected custom CA. Specifically, it intercepts com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket->verifyCertificateChain, com.google.android.gms.org.conscrypt.Platform->checkTrusted/checkServerTrusted, and com.android.org.conscrypt.TrustManagerImpl->checkTrustedRecursive. For each, it reconstructs an X509Certificate[] chain when needed (from DER byte[][]), validates it with the custom X509TrustManager, and, if trusted, returns a successful result (e.g., Arrays.asList(chain)), otherwise defers to the original logic. This preserves normal TLS protections for all other traffic while allowing connections signed by the configured CA to proceed.

**Comment by rams3sh** [comment]
@pimterry 
I was facing the issue (as posted in my previous message) in Android 36 version. But when I used  the same app with same version that I was debugging earlier with Android 34, it worked. 

This is a private app, so I am unable to share it. But I think there is some changes in the new version of android, that results in this error.
